export const foods = [
  {
    ID: "FOODBEVE0001",
    Ảnh: "images/TraDao.jpg",
    Tên: "Trà đào cam sả",
    Cửa_Hàng: "Quán trà đào ngon",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Đồ uống",
    Giá: 40000,
    Mô_tả: "Trà đào cam sả thơm ngon, mát lạnh, giải nhiệt ngày hè.",
  },
  {
    ID: "FOODMAIN0001",
    Ảnh: "images/BoKho.jpg",
    Tên: "Bò kho",
    Cửa_Hàng: "Quán bò kho ngon",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 60000,
    Mô_tả: "Bò kho đậm đà, ăn kèm bánh mì hoặc hủ tiếu.",
  },
  {
    ID: "FOODMAIN0002",
    Ảnh: "images/LauGaLaE.jpg",
    Tên: "Lẩu gà lá é",
    Cửa_Hàng: "Nhà hàng Đà Lạt",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 250000,
    Mô_tả: "Lẩu gà lá é thơm ngon, đậm vị với thịt gà tươi và lá é đặc trưng.",
  },
  {
    ID: "FOODMAIN0003", 
    Ảnh: "images/BanhCanh.jpg",
    Tên: "Bánh canh cua",
    Cửa_Hàng: "Quán bánh canh cua Cô Ba",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 60000,
    Mô_tả: "Bánh canh cua thơm ngon với thịt cua tươi, giò heo và nước dùng đậm đà.",
  },
  {
    ID: "FOODFAST0001", 
    Ảnh: "images/BanhXeo.jpg",
    Tên: "Bánh xèo",
    Cửa_Hàng: "Quán bánh xèo miền Tây",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 30000,
    Mô_tả: "Bánh xèo giòn rụm với tôm, thịt và giá đỗ, ăn kèm rau sống và nước mắm chua ngọt.",
  },
  {
    ID: "FOODSNAK0001", 
    Ảnh: "images/BanhTrangMe.jpg",
    Tên: "Bánh tráng mè",
    Cửa_Hàng: "Quán bánh tráng mè Sài Gòn",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Đồ ăn vặt",
    Giá: 25000,
    Mô_tả: "Bánh tráng mè giòn rụm, thơm ngon, ăn kèm nước chấm đặc biệt.",
  },
  {
    ID: "FOODSNAK0002", 
    Ảnh: "images/CheBuoi.jpg",
    Tên: "Chè bưởi",
    Cửa_Hàng: "Quán chè bưởi Cần Thơ",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Đồ ăn vặt",
    Giá: 30000,
    Mô_tả: "Chè bưởi thơm ngon với cùi bưởi giòn, nước cốt dừa béo ngậy.",
  },
  {
    ID: "FOODMAIN0004", 
    Ảnh: "images/ComGaHoiAn.jpg",
    Tên: "Cơm gà Hội An",
    Cửa_Hàng: "Quán cơm gà Hội An",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 60000,
    Mô_tả: "Cơm gà Hội An thơm ngon, ăn kèm rau sống và nước mắm chua ngọt.",
  },
  {
    ID: "FOODFAST0002", 
    Ảnh: "images/pizzahs.jpg",
    Tên: "Pizza hải sản",
    Cửa_Hàng: "Pizza Hut",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Đồ ăn nhanh",
    Giá: 150000,
    Mô_tả: "Pizza hải sản với tôm, mực, phô mai béo ngậy và sốt đặc biệt.",
  },
  {
    ID: "FOODFAST0003", 
    Ảnh: "images/BanhGio.jpg",
    Tên: "Bánh giò",
    Cửa_Hàng: "Quán bánh giò Hà Nội",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 20000,
    Mô_tả: "Bánh giò mềm mịn với nhân thịt băm, mộc nhĩ và hành phi thơm ngon.",
  },
  {
    ID: "FOODFAST0004",
    Ảnh: "images/Hamburger.jpg",
    Tên: "Hamburger",
    Cửa_Hàng: "McDonald's",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 60000,
    Mô_tả: "Hamburger với thịt bò nướng, rau sống và sốt đặc biệt.",
  },
  {
    ID: "FOODMAIN0005",
    Ảnh: "images/SupCua.jpg",
    Tên: "Súp cua",
    Cửa_Hàng: "Nhà hàng Hải sản",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 45000,
    Mô_tả: "Súp cua thơm ngon, đậm vị với trứng, nấm và thịt cua tươi.",
  },
  {
    ID: "FOODMAIN0006",
    Ảnh: "images/Bone.jpg",
    Tên: "Bò né",
    Cửa_Hàng: "Quán bò né Sài Gòn",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 55000,
    Mô_tả: "Bò né nóng hổi, ăn kèm trứng ốp la, pate và bánh mì.",
  },
  {
    ID: "FOODMAIN0007",
    Ảnh: "images/xoiga.jpg",
    Tên: "Xôi gà",
    Cửa_Hàng: "Quán xôi gà Bắc Hà",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 40000,
    Mô_tả: "Xôi gà thơm ngon với thịt gà xé và hành phi giòn rụm.",
  },
  {
    ID: "FOODFAST0005",
    Ảnh: "images/Banhbao.jpg",
    Tên: "Bánh bao",
    Cửa_Hàng: "Quán bánh bao Hà Nội",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Bánh",
    Giá: 20000,
    Mô_tả: "Bánh bao nhân thịt trứng cút, lớp vỏ mềm mịn hấp dẫn.",
  },
  {
    ID: "FOODFAST0006",
    Ảnh: "images/MT.jpg",
    Tên: "Mì tôm",
    Cửa_Hàng: "Quán mì tôm Sài Gòn",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 15000,
    Mô_tả: "Mì tôm nóng hổi, ăn kèm trứng, thịt bò và rau xanh.",
  },
  {
    ID: "FOODSNAK0003",
    Ảnh: "images/goicuon.jpg",
    Tên: "Gỏi cuốn",
    Cửa_Hàng: "Quán Gỏi Cuốn 123",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhẹ",
    Giá: 30000,
    Mô_tả: "Gỏi cuốn tươi ngon với tôm, thịt, rau sống và chấm nước mắm chua ngọt.",
  },
  {
    ID: "FOODBEVE0005",
    Ảnh: "images/TraSua.jpg",
    Tên: "Trà sữa trân châu",
    Cửa_Hàng: "Trà Sữa Ding Tea",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Đồ uống",
    Giá: 45000,
    Mô_tả: "Trà sữa thơm béo với trân châu dai giòn hấp dẫn.",
  },
  {
    ID: "FOODMAIN0008",
    Ảnh: "images/lauthai.jpg",
    Tên: "Lẩu Thái",
    Cửa_Hàng: "Nhà hàng Lẩu Thái",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 250000,
    Mô_tả: "Lẩu Thái chua cay với tôm, mực, thịt bò và rau xanh.",
  },
  {
    ID: "FOODMAIN0009",
    Ảnh: "images/chaolong.jpg",
    Tên: "Cháo lòng",
    Cửa_Hàng: "Quán cháo lòng Cô Ba",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 40000,
    Mô_tả: "Cháo lòng nóng hổi, ăn kèm lòng heo, quẩy và rau thơm.",
  },
  {
    ID: "FOODFAST0007",
    Ảnh: "images/BMKT.jpg",
    Tên: "Bánh mì kẹp thịt nướng",
    Cửa_Hàng: "Bánh mì Ba Lê",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 35000,
    Mô_tả: "Bánh mì kẹp thịt nướng thơm ngon, ăn kèm rau sống và sốt đặc biệt.",
  },
  {
    ID: "FOODMAIN0010",
    Ảnh: "images/PB.jpg",
    Tên: "Phở bò tái",
    Cửa_Hàng: "Quán Phở Hương",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 55000,
    Mô_tả: "Phở bò tái với nước dùng đậm đà và thịt bò mềm ngon.",
  },
  {
    ID: "FOODMAIN0011",
    Ảnh: "images/BC.jpg",
    Tên: "Bún chả Hà Nội",
    Cửa_Hàng: "Quán Bún chả Hà Nội",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 45000,
    Mô_tả: "Bún chả với thịt nướng thơm ngon, ăn kèm nước chấm đậm đà.",
  },
  {
    ID: "FOODFAST0008",
    Ảnh: "images/GaKFC.jpg",
    Tên: "Gà rán KFC",
    Cửa_Hàng: "KFC",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 70000,
    Mô_tả: "Gà rán giòn rụm với lớp vỏ vàng ruộm và thịt mềm ngọt.",
  },
  {
    ID: "FOODMAIN0012",
    Ảnh: "images/Sushi.jpg",
    Tên: "Sushi cá hồi",
    Cửa_Hàng: "Nhà hàng Nhật Bản",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Đồ ăn Nhật",
    Giá: 150000,
    Mô_tả: "Sushi cá hồi tươi ngon với cá hồi, tôm, và các loại hải sản đặc biệt.",
  },
  {
    ID: "FOODSNAK0004",
    Ảnh: "images/BanhTrangCuon.jpg",
    Tên: "Bánh tráng cuốn",
    Cửa_Hàng: "Quán bánh tráng cuốn Tây Ninh",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Đồ ăn vặt",
    Giá: 30000,
    Mô_tả: "Bánh tráng cuốn với rau sống, thịt luộc và nước chấm me.",
  },
  {
    ID: "FOODDESS0006",
    Ảnh: "images/che-thai.jpg",
    Tên: "Chè Thái",
    Cửa_Hàng: "Quán chè Thái Lan",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Tráng miệng",
    Giá: 35000,
    Mô_tả: "Chè Thái thơm ngon với sầu riêng, thạch và nước cốt dừa béo ngậy.",
  },
  {
    ID: "FOODMAIN0013",
    Ảnh: "images/GaXoiMo.jpg",
    Tên: "Cơm gà xối mỡ",
    Cửa_Hàng: "Quán cơm gà Gia Lai",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 50000,
    Mô_tả: "Cơm gà giòn ngon, ăn kèm nước mắm chua ngọt và rau sống.",
  },
  {
    ID: "FOODBEVE0006",
    Ảnh: "images/TraChanh.jpg",
    Tên: "Trà chanh",
    Cửa_Hàng: "Quán trà chanh Hà Nội",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Đồ uống",
    Giá: 15000,
    Mô_tả: "Trà chanh mát lạnh, thơm ngon, giải khát ngày hè.",
  },
  {
    ID: "FOODDESS0007",
    Ảnh: "images/Flan.jpg",
    Tên: "Bánh flan",
    Cửa_Hàng: "Quán bánh flan ngon",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Tráng miệng",
    Giá: 25000,
    Mô_tả: "Bánh flan mềm mịn, thơm ngon, tan ngay trong miệng.",
  },
  {
    ID: "FOODMAIN0014",
    Ảnh: "images/BunBoHue.jpg",
    Tên: "Bún bò Huế",
    Cửa_Hàng: "Quán bún bò Huế",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 60000,
    Mô_tả: "Bún bò Huế với nước dùng đậm đà và thịt bò mềm ngon.",
  },
  {
    ID: "FOODMAIN0015",
    Ảnh: "images/ComTam.jpg",
    Tên: "Cơm tấm",
    Cửa_Hàng: "Quán cơm tấm Sài Gòn",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 40000,
    Mô_tả: "Cơm tấm với thịt nướng, trứng ốp la và nước mắm chua ngọt.",
  },
  {
    ID: "FOODFAST0009",
    Ảnh: "images/BanhCuon.jpg",
    Tên: "Bánh cuốn",
    Cửa_Hàng: "Quán bánh cuốn Hà Nội",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 30000,
    Mô_tả: "Bánh cuốn với thịt lợn, nấm và nước mắm đặc biệt.",
  },
  {
    ID: "FOODFAST0010",
    Ảnh: "images/XoiXeo.jpg",
    Tên: "Xôi xéo",
    Cửa_Hàng: "Quán xôi xéo ngon",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 25000,
    Mô_tả: "Xôi xéo với đậu xanh, thịt lợn và nước mắm đặc biệt.",
  },
  {
    ID: "FOODMAIN0016",
    Ảnh: "images/ComChien.jpg",
    Tên: "Cơm chiên Dương Châu",
    Cửa_Hàng: "Nhà hàng Trung Hoa",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 50000,
    Mô_tả: "Cơm chiên Dương Châu với tôm, trứng, lạp xưởng và rau củ.",
  },
  {
    ID: "FOODFAST0011",
    Ảnh: "images/ChaoLong.jpg",
    Tên: "Cháo lòng",
    Cửa_Hàng: "Quán cháo lòng ngon",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 30000,
    Mô_tả: "Cháo lòng với lòng heo, thịt lợn và nước mắm đặc biệt.",
  },
  {
    ID: "FOODFAST0012",
    Ảnh: "images/BanhKhot.jpg",
    Tên: "Bánh khọt",
    Cửa_Hàng: "Quán bánh khọt Vũng Tàu",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 25000,
    Mô_tả: "Bánh khọt với tôm, thịt lợn và nước mắm đặc biệt.",
  },
  {
    ID: "FOODFAST0013",
    Ảnh: "images/XoiGac.jpg",
    Tên: "Xôi gấc",
    Cửa_Hàng: "Quán xôi gấc ngon",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 20000,
    Mô_tả: "Xôi gấc với gấc, thịt lợn và nước mắm đặc biệt.",
  },
  {
    ID: "FOODFAST0014",
    Ảnh: "images/BanhBeo.jpg",
    Tên: "Bánh bèo",
    Cửa_Hàng: "Quán bánh bèo Huế",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 25000,
    Mô_tả: "Bánh bèo với tôm, thịt lợn và nước mắm đặc biệt.",
  },
  {
    ID: "FOODFAST0015",
    Ảnh: "images/BanhBotLoc.jpg",
    Tên: "Bánh bột lọc",
    Cửa_Hàng: "Quán bánh bột lọc ngon",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhanh",
    Giá: 25000,
    Mô_tả: "Bánh bột lọc với tôm, thịt lợn và nước mắm đặc biệt.",
  },
  {
    ID: "FOODDESS0008",
    Ảnh: "images/BanhDauXanh.jpg",
    Tên: "Bánh đậu xanh",
    Cửa_Hàng: "Tiệm bánh đậu xanh Hải Dương",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Bánh",
    Giá: 30000,
    Mô_tả: "Bánh đậu xanh thơm ngon, tan ngay trong miệng, đặc sản Hải Dương.",
  },
  {
    ID: "FOODMAIN0017",
    Ảnh: "images/LauBo.jpg",
    Tên: "Lẩu bò",
    Cửa_Hàng: "Nhà hàng lẩu bò 5 Sao",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 280000,
    Mô_tả: "Lẩu bò đậm vị với thịt bò mềm, rau xanh và nước dùng đặc biệt.",
  },
  {
    ID: "FOODSNAK0005",
    Ảnh: "images/BanhTrangNuong.jpg",
    Tên: "Bánh tráng nướng",
    Cửa_Hàng: "Quán bánh tráng nướng Đà Lạt",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Đồ ăn vặt",
    Giá: 20000,
    Mô_tả: "Bánh tráng nướng giòn rụm với trứng, xúc xích và hành phi.",
  },
  {
    ID: "FOODSNAK0006",
    Ảnh: "images/BanhItTran.jpg",
    Tên: "Bánh ít trần",
    Cửa_Hàng: "Quán bánh Huế",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn vặt",
    Giá: 25000,
    Mô_tả: "Bánh ít trần dẻo mềm với nhân tôm thịt, chấm nước mắm chua ngọt.",
  },
  {
    ID: "FOODMAIN0018",
    Ảnh: "images/BoLucLac.jpg",
    Tên: "Bò lúc lắc",
    Cửa_Hàng: "Nhà hàng Beef Steak",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 120000,
    Mô_tả: "Bò lúc lắc mềm thơm, ăn kèm khoai tây chiên và sốt tiêu đen.",
  },
  {
    ID: "FOODMAIN0019",
    Ảnh: "images/ChaCa.jpg",
    Tên: "Chả cá Lã Vọng",
    Cửa_Hàng: "Quán chả cá Hà Nội",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 180000,
    Mô_tả: "Chả cá Lã Vọng thơm ngon với rau thì là, bún và mắm tôm.",
  },
  {
    ID: "FOODSNAK0007",
    Ảnh: "images/MitTron.jpg",
    Tên: "Mít trộn",
    Cửa_Hàng: "Quán gỏi mít Đà Nẵng",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Đồ ăn vặt",
    Giá: 30000,
    Mô_tả: "Mít trộn chua ngọt với tôm khô, đậu phộng và rau thơm.",
  },
  {
    ID: "FOODMAIN0020",
    Ảnh: "images/OcLenXaoDua.jpg",
    Tên: "Ốc len xào dừa",
    Cửa_Hàng: "Quán ốc Sài Gòn",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Hải sản",
    Giá: 70000,
    Mô_tả: "Ốc len xào dừa béo ngậy, thơm ngon với nước cốt dừa đặc biệt.",
  },
  {
    ID: "FOODSNAK0008",
    Ảnh: "images/ChaGio.jpg",
    Tên: "Chả giò",
    Cửa_Hàng: "Quán ăn gia đình",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món ăn nhẹ",
    Giá: 40000,
    Mô_tả: "Chả giò giòn rụm với nhân thịt, nấm mèo, ăn kèm nước mắm chua ngọt.",
  },
  {
    ID: "FOODMAIN0021",
    Ảnh: "images/HuTieuNamVang.jpg",
    Tên: "Hủ tiếu Nam Vang",
    Cửa_Hàng: "Quán hủ tiếu Mỹ Tho",
    Trạng_Thái: "Còn hàng",
    Danh_Mục: "Món chính",
    Giá: 50000,
    Mô_tả: "Hủ tiếu Nam Vang với tôm, thịt bằm, trứng cút và nước dùng đậm đà.",
  },
];

